---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# Configure golangci-lint
# Source: https://golangci-lint.run/usage/linters/
issues:
  exclude-rules:
    - path: "`*test.go`"
      linters:
        - gosec
        - goconst
        - revive
    - path: testing\.go
      linters:
        - gosec
        - goconst
        - revive
linters:
  enable:
    - revive
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - goconst
    - goimports
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true